# Generated by Django 5.2.3 on 2025-06-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('housing', 'Housing / Shelter'), ('transportation', 'Transportation'), ('medical', 'Medical'), ('work', 'Work'), ('social', 'Social')], max_length=50),
        ),
    ]
