# Generated by Django 5.2.3 on 2025-06-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
