# Generated by Django 6.0.2 on 2026-03-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_tag_resource_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('psychiatric-inpatient', 'Psychiatric Inpatient'), ('general-medical', 'General Medical'), ('substance-use', 'Substance Use'), ('dental', 'Dental'), ('emergency-shelter', 'Emergency Shelter'), ('housing-rental-assistance', 'Housing & Rental Assistance'), ('temporary-transitional', 'Temporary & Transitional'), ('clothing', 'Clothing'), ('education-career-development', 'Education & Career Development'), ('financial', 'Financial'), ('legal', 'Legal'), ('deaf', 'Deaf'), ('domestic-violence', 'Domestic Violence'), ('hiv-aids', 'HIV / AIDS'), ('first-responders', 'First Responders'), ('idd', 'IDD'), ('pregnancy', 'Pregnancy'), ('veterans', 'Veterans')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('medical-mental-health', 'Medical and Mental Health'), ('housing-shelter', 'Housing and Shelter'), ('social-services', 'Social Services'), ('specialized-services', 'Specialized Services')], max_length=50),
        ),
    ]
