# Generated by Django 6.0.2 on 2026-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resource_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('mental health ', 'Mental Health'), ('medical', ' Medical'), ('substance-use', 'Substance Use'), ('dental', 'Dental'), ('emergency-shelter', 'Emergency Shelter'), ('housing-rental-assistance', 'Housing & Rental Assistance'), ('temporary-transitional', 'Temporary & Transitional'), ('transportation', 'Transportation'), ('clothing', 'Clothing'), ('education-career-development', 'Education & Career Development'), ('financial', 'Financial'), ('legal', 'Legal'), ('deaf', 'Deaf'), ('domestic-violence', 'Domestic Violence'), ('hiv-aids', 'HIV / AIDS'), ('first-responders', 'First Responders'), ('idd', 'IDD'), ('pregnancy', 'Pregnancy'), ('veterans', 'Veterans')], max_length=50),
        ),
    ]
